- hosts: localhost
  gather_facts: yes
  become: no
  vars_files: ../vars/vars.yml

  tasks:
    - name: check the yml file for updates
    　shell: cd ~/WebInfo_Manege && git pull
     
    - name: make new git branch
      shell: cd ~/WebInfo_Manage && git checkout -b `date +%Y%m%d`

- hosts: web
  gather_facts: yes
  become: yes
  become_user: root
  vars_files: ../vars/vars.yml

  tasks:
    - name: convert html file to txt
      shell: cat {{ contents_path }}{{ target_file_name }}.html  > {{ contents_path }}{{ target_file_name }}_`date +%Y%m%d`.txt

    - name: txt files scp to CollectSV
      shell: scp {{ contents_path }}{{ target_file_name }}_`date +%Y%m%d`.txt ansible@192.168.33.200:{{ git_dir }}

- hosts: localhost
  gather_facts: no
  become: no
  vars_files: ../vars/vars.yml

  tasks:
    - name: commit additional files
      shell: cd ~/WebInfo_Manage && git add .

    - name: add commit message
      shell: git commit -m "`date +%Y%m%d`_GetWebInfo"

    - name: push today's branch
      shell: git push origin `date +%Y%m%d`

    - name: delete local Branch
      shell: git checkout main && git branch -D `date +%Y%m%d`
